version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dev
    networks:
      - dev-network
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    networks:
      - dev-network
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis
      - ./redis/configurations/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  dev-network:
    name: dev-network
volumes:
  dev-db-data:
  redis_data:
